name: Scientist.DependencyInjection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  major: 1
  minor: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set Build Number 
      shell: pwsh
      run: |
        $Branch= "${{github.ref}}"
        $BranchName= "${{github.ref_name}}".ToLower()

        if ('${{github.event_name }}' -eq 'pull_request')
        {
          $BranchName = "PR${{github.event.number}}"
        }
        
        git fetch --tags
        $LastTag = git tag --sort=-version:refname -l [v][0-9].[0-9].[0-9] | Select-Object -First 1
        $Date = (Get-Date).ToUniversalTime().ToString("yyyyMMdd-HHmmss")

        Write-Host "Last Tag: $LastTag"

        if ($LastTag -ne $null)
        {
          $LastTag = $LastTag.TrimStart("v")
          $Major = '${{github.ref}}' -eq 'refs/heads/main' ? ${{ env.major }} : $LastTag.Split(".")[0]
          $Minor = '${{github.ref}}' -eq 'refs/heads/main' ? ${{ env.minor }} : $LastTag.Split(".")[1] 
          $Patch = '${{github.ref}}' -eq 'refs/heads/main' && ${{ env.major }} -eq $LastTag.Split(".")[0] && ${{ env.minor }} -eq $LastTag.Split(".")[1]  ? [string]([int]$LastTag.Split(".")[2] + 1) : 0
          $BuildNo = "$Major.$Minor.$Patch"
        }
        else 
        {
          $BuildNo = "0.0.0"
        }

        if ($Branch -ne 'refs/heads/main')
        {
          $BuildNo = $BuildNo + "-$BranchName-$Date"
        }

        Write-Host "BuildNo: $BuildNo"
        echo "BuildNo=$BuildNo" | Out-File -FilePath ${{github.env}} -Encoding utf-8 -Append
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack Scientist.DependencyInjection/Scientist.DependencyInjection.csproj /p:Configuration=Release --output ~/packages /p:PackageVersion=$BuildNo --verbosity Detailed
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ~/packages/**/*.nupkg
    - name: Tag commit
      shell: pwsh
      if: ${{ github.ref == 'refs/heads/main'}}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git tag -a "v$env:BuildNo" -m "Increment Build No"
        git push origin "v$env:BuildNo"
  deployment: 
    runs-on: ubuntu-latest
    environment: Nuget
    if: ${{ github.ref == 'refs/heads/main'}}
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: packages  
    - name: Publish
      if: equals(${{github.ref}}, 'refs/heads/main')
      run: nuget push **\Scientist.DependencyInjection*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_PAT}}
