name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack Scientist.DependencyInjection/Scientist.DependencyInjection.csproj /p:Configuration=Release --output ~/packages /p:PackageVersion=0.0.$GITHUB_RUN_NUMBER --verbosity Detailed
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ~/packages/**/*.nupkg
